using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Roughcut.Atlassian.Integration.Tests.Models
{
    // <auto-generated />
    //
    // To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
    //
    //    using QuickType;
    //
    //    var models = Models.FromJson(jsonString);

    namespace QuickType
    {
        using System;
        using System.Collections.Generic;
        using Newtonsoft.Json;


        public  class ProjectElement
        {
            [JsonProperty("self", NullValueHandling = NullValueHandling.Ignore)]
            public Uri Self { get; set; }

            [JsonProperty("id", NullValueHandling = NullValueHandling.Ignore)]
            [JsonConverter(typeof(ParseStringConverter))]
            public long? Id { get; set; }

            [JsonProperty("key", NullValueHandling = NullValueHandling.Ignore)]
            public string Key { get; set; }

            [JsonProperty("name", NullValueHandling = NullValueHandling.Ignore)]
            public string Name { get; set; }

            [JsonProperty("avatarUrls", NullValueHandling = NullValueHandling.Ignore)]
            public AvatarUrls AvatarUrls { get; set; }

            [JsonProperty("issuetypes", NullValueHandling = NullValueHandling.Ignore)]
            public List<Issuetype> Issuetypes { get; set; }
        }
    }

}
