//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.3.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------


using Roughcut.Atlassian.ClientServices.Base;
using Roughcut.Atlassian.ClientServices.Helpers;

namespace MyNamespace
{
    #pragma warning disable // Disable all warnings

    //[System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.8.0.0 (Newtonsoft.Json v13.0.3.0)")]
    //public partial class SecretsBase
    //{
    //    [Newtonsoft.Json.JsonProperty("Secret1", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    //    public string Secret1 { get; set; }

    //    [Newtonsoft.Json.JsonProperty("Secret2", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    //    public string Secret2 { get; set; }



    //    private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

    //    [Newtonsoft.Json.JsonExtensionData]
    //    public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
    //    {
    //        get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
    //        set { _additionalProperties = value; }
    //    }

    //}


}